import { db } from "./firebase.js";

import {

collection,
getDocs

}

from

"https://www.gstatic.com/firebasejs/10.13.2/firebase-firestore.js";

const username =
sessionStorage.getItem(
"username"
);

const roomCode =
sessionStorage.getItem(
"roomCode"
);

if(!roomCode){

window.location.href =
"index.html";

}

document.getElementById(
"receiptInfo"
).innerHTML =

`
<p>
Room Code:
<b>${roomCode}</b>
</p>

<p>
Generated By:
<b>${username}</b>
</p>

<p>
Date:
<b>
${new Date().toLocaleString()}
</b>
</p>
`;

loadReceipt();

async function loadReceipt(){

const snapshot =
await getDocs(

collection(
db,
"rooms",
roomCode,
"cart"
)

);

const receiptDiv =
document.getElementById(
"receiptItems"
);

receiptDiv.innerHTML = "";

let totalQty = 0;

let grandTotal = 0;

snapshot.forEach(item=>{

const data =
item.data();

const itemTotal =
(data.price || 0) *
data.quantity;

totalQty +=
data.quantity;

grandTotal +=
itemTotal;

receiptDiv.innerHTML +=

`
<div class="receipt-row">

<div>

<b>${data.name}</b>

<br>

${data.category}

<br>

Added By:
${data.addedBy}

</div>

<div>

${
data.price > 0
?
"₹" + data.price
:
"N/A"
}

x

${data.quantity}

=

₹${itemTotal}

</div>

</div>
`;

});

document.getElementById(
"totalQuantity"
).innerText =

"Total Quantity: " +
totalQty;

document.getElementById(
"grandTotal"
).innerText =

"Grand Total: ₹" +
grandTotal;

}

window.goBack =
function(){

window.location.href =
"room.html";

};